name: Django CI

on:
  push:
    branches: [ main, dev, beforedev-2 ]
  pull_request:
    branches: [ dev, beforedev-2 ]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      matrix:
        python-version: [3.9]
    services:
      mysql:
        image: mysql:5.7
        env:
          MYSQL_ROOT_PASSWORD: ${{ secrets.PASSWORD }}
          MYSQL_DATABASE: ${{ secrets.DB_NAME }}
        ports: ['3306:3306']

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    #     pip install coverage
    - name: Make migrations
      run: |
        python manage.py makemigrations
        python manage.py migrate
      env:
        SECRET_KEY: ${{ secrets.SECRET_KEY }}
        ENGINE: ${{ secrets.ENGINE }}
        DB_NAME: ${{ secrets.DB_NAME }}
        USER: root
        PASSWORD: ${{ secrets.PASSWORD }}
        HOST: ${{ secrets.HOST }}
        PORT: ${{ secrets.PORT }}
    - name: Run Tests
      run: |
        python manage.py test
      env:
        SECRET_KEY: ${{ secrets.SECRET_KEY }}
        ENGINE: ${{ secrets.ENGINE }}
        DB_NAME: ${{ secrets.DB_NAME }}
        USER: root
        PASSWORD: ${{ secrets.PASSWORD }}
        HOST: ${{ secrets.HOST }}
        PORT: ${{ secrets.PORT }}
    # - name: Run coverage
    #   run: |
    #     coverage run manage.py test && coverage report